name: App Mockup
description: Make Pergect Screenshots For Apps.
full_description: '
Use modern text recognition technology to quickly and high-quality recognize text on pictures. 
<br>Free, no limit on the number of scans!<br>

<br>Most accurate OCR scanner app with 99%+ accuracy and supporting most popular 60+ languages in the world.
<br>
<br><strong>Features of Text Scanner</strong>
<br>- World highest speed reading
<br>- World highest accuracy reading
<br>- Support photos of your album
<br>- Support more than 60+ languages
<br>- Support handwriting
<br>.....
'
android: https://play.google.com/store/apps/details?id=com.spaceship.ocr.textscanner.imagetotext
iOS: https://apps.apple.com/us/id1527077682
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
